development:
  adapter: postgresql
  encoding: unicode
  database: food_ordering_development
  host: localhost
  pool: 5
  username: kirill
  password: 123qwe

test:
  adapter: postgresql
  encoding: unicode
  database: food_ordering_test
  host: localhost
  pool: 5
  username: kirill
  password: 123qwe

production:
  adapter: postgresql
  encoding: unicode
  database: pasha_foodord83
  host: postgresql2.locum.ru
  pool: 5
  username: pasha_foodord83
  password: foodord