development:
  adapter: postgresql
  encoding: unicode
  database: food_ordering_development
  host: localhost
  pool: 5
  username: postgres
  password: 123qwe

test:
  adapter: postgresql
  encoding: unicode
  database: food_ordering_development
  host: localhost
  pool: 5
  username: postgres
  password: 123qwe

production:
  adapter: postgresql
  encoding: unicode
  database: food_ordering_development
  host: localhost
  pool: 5
  username: postgres
  password: 123qwe